name: Generate Go from Proto

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          # We also need this to handle the timestamp.proto imports
          git clone --depth 1 https://github.com/googleapis/googleapis.git
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/yerkebulan111/ap-2_protos.git

      - name: Clone Generated Code Repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/yerkebulan111/ap-2_protos-gen.git

      - name: Generate Go Code from Proto Files
        run: |
          # Use the EXACT name from the clone step above
          cd ap-2_protos
          protoc \
            --go_out=../ap-2_protos-gen \
            --go_opt=paths=source_relative \
            --go-grpc_out=../ap-2_protos-gen \
            --go-grpc_opt=paths=source_relative \
            -I . \
            -I ../googleapis \
            payment/payment.proto \
            order/order.proto

      - name: Push Generated Files
        run: |
          # Use the EXACT name from the clone step above
          cd ap-2_protos-gen
          git config user.email "yerkebulan111@users.noreply.github.com"
          git config user.name "yerkebulan111"
          git add .
          # The || true prevents the script from failing if there are no changes to commit
          git commit -m "auto: regenerate from proto" || echo "No changes to commit"
          git push origin main